# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 23:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', localflavor.us.models.PhoneNumberField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of the retailer such as Casper', max_length=128)),
                ('web', models.CharField(help_text='Enter web address of the retailer such as casper.com', max_length=128)),
                ('description', models.TextField(help_text='Enter a brief description of the retailer', max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('phone', localflavor.us.models.PhoneNumberField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiate_date', models.DateField(default=datetime.date.today)),
                ('container_shipped', models.BooleanField(default=False)),
                ('container_delivered', models.BooleanField(default=False)),
                ('kit_shipped', models.BooleanField(default=False)),
                ('kit_delivered', models.BooleanField(default=False)),
                ('container_back_shipped', models.BooleanField(default=False)),
                ('container_back_delivered', models.BooleanField(default=False)),
                ('kit_back_shipped', models.BooleanField(default=False)),
                ('kit_back_delivered', models.BooleanField(default=False)),
                ('rma_number', models.CharField(max_length=128, verbose_name='RMA#')),
                ('order_number', models.CharField(max_length=128, verbose_name='Order#')),
                ('invoice_number', models.CharField(max_length=128, verbose_name='Invoice#')),
                ('order_date', models.DateField()),
                ('return_authorized', models.BooleanField()),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('size', models.CharField(choices=[('TWIN', 'Twin'), ('TWIN_XL', 'Twin XL'), ('FULL', 'Full'), ('QUEEN', 'Queen'), ('KING', 'King'), ('CAL_KING', 'Cal King')], help_text='Mattress size', max_length=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mattress.Buyer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mattress.OnlineRetailer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(max_length=128, verbose_name='RMA#')),
                ('order_number', models.CharField(max_length=128, verbose_name='Order#')),
                ('invoice_number', models.CharField(max_length=128, verbose_name='Invoice#')),
                ('order_date', models.DateField()),
                ('return_authorized', models.BooleanField()),
                ('brand', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('size', models.CharField(choices=[('TWIN', 'Twin'), ('TWIN_XL', 'Twin XL'), ('FULL', 'Full'), ('QUEEN', 'Queen'), ('KING', 'King'), ('CAL_KING', 'Cal King')], help_text='Mattress size', max_length=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mattress.Buyer')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mattress.OnlineRetailer')),
            ],
        ),
        migrations.CreateModel(
            name='UsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=128, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="Address Cont'd")),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(max_length=2, verbose_name='State')),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10, verbose_name='Zip Code')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mattress.UsAddress'),
        ),
    ]
